# Generated by Django 4.2.4 on 2023-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Род растения')),
            ],
            options={
                'verbose_name': 'Род растения',
                'verbose_name_plural': 'Роды растений',
            },
        ),
        migrations.AlterField(
            model_name='flower',
            name='genus',
            field=models.CharField(max_length=40, verbose_name='Род растения'),
        ),
    ]
