# Generated by Django 4.2.4 on 2023-08-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopbot', '0002_genus_alter_flower_genus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='flower',
            name='genus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shopbot.genus', verbose_name='Род растения'),
        ),
    ]
