# Generated by Django 4.2.4 on 2023-08-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopbot', '0004_alter_flower_genus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='gamma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultings', to='shopbot.gamma', verbose_name='Гамма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('processing', 'В обработке'), ('ready', 'Готов'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=40, null=True, verbose_name='Статус'),
        ),
    ]
