# Generated by Django 4.2.4 on 2023-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbot', '0005_alter_consulting_gamma_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя'),
        ),
    ]
